name: "CI - Start"
concurrency:
  group: ci-start-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
env:
  PYTHON_VERSION: 3.9.10
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ env.PYTHON_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9.10"
      - uses: pre-commit/action@v2.0.2
