name: "Generate documentation"
on:
  push:
    branches: [main]
jobs:
  make_docs:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ env.PYTHON_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9.10"
      - uses: pre-commit/action@v2.0.2
        with:
          extra_args: --hook-stage manual
      - name: Create PR with new version numbers
        if: failure()
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update-readme
          title: "Update README.md"
